FROM golang
MAINTAINER Karthik Gaekwad

RUN go get github.com/prometheus/client_golang/prometheus
RUN go get github.com/prometheus/client_golang/prometheus/promhttp
COPY . /go/src/github.com/karthequian/ecommerce/src
WORKDIR /go/src/github.com/karthequian/ecommerce/src/users
RUN go get && go build -o /bin/auth

ENTRYPOINT ["/bin/auth"]